SOURCES += \
    Elements/FactoryMethod/Creators/coincreator.cpp \
    Elements/FactoryMethod/Creators/floorcreator.cpp \
    Elements/FactoryMethod/Creators/healthcreator.cpp \
    Elements/FactoryMethod/Creators/lavacreator.cpp \
    Elements/FactoryMethod/Creators/wallcreator.cpp \
    Elements/FactoryMethod/Products/coin.cpp \
    Elements/FactoryMethod/Products/floor.cpp \
    Elements/FactoryMethod/Products/health.cpp \
    Elements/FactoryMethod/Products/lava.cpp \
    Elements/FactoryMethod/Products/wall.cpp \
    Elements/Strategy/coinstrategy.cpp \
    Elements/Strategy/healthstrategy.cpp \
    Elements/Strategy/lavastrategy.cpp \
    Field/cell.cpp \
    Field/playingfield.cpp \
    Game/Command/configurelog.cpp \
    Game/Command/exitgame.cpp \
    Game/Command/move.cpp \
    Game/Command/newgame.cpp \
    Game/enemyturn.cpp \
    Game/game.cpp \
    Game/gameloader.cpp \
    Game/gamesaver.cpp \
    Game/playerturn.cpp \
    Log/consolelog.cpp \
    Log/filelog.cpp \
    Log/log.cpp \
    Log/multiplelog.cpp \
    UDG/fieldwidget.cpp \
    UDG/untitleddesktopgame.cpp \
    Units/enemy.cpp \
    Units/ienemy.cpp \
    Units/player.cpp

HEADERS += \
    Elements/FactoryMethod/Creators/coincreator.h \
    Elements/FactoryMethod/Creators/creator.h \
    Elements/FactoryMethod/Creators/floorcreator.h \
    Elements/FactoryMethod/Creators/healthcreator.h \
    Elements/FactoryMethod/Creators/lavacreator.h \
    Elements/FactoryMethod/Creators/wallcreator.h \
    Elements/FactoryMethod/Products/coin.h \
    Elements/FactoryMethod/Products/floor.h \
    Elements/FactoryMethod/Products/health.h \
    Elements/FactoryMethod/Products/ielement.h \
    Elements/FactoryMethod/Products/lava.h \
    Elements/FactoryMethod/Products/wall.h \
    Elements/Strategy/coinstrategy.h \
    Elements/Strategy/healthstrategy.h \
    Elements/Strategy/iinteractionstrategy.h \
    Elements/Strategy/lavastrategy.h \
    Elements/iusableelement.h \
    Field/cell.h \
    Field/playingfield.h \
    Game/Command/configurelog.h \
    Game/Command/exitgame.h \
    Game/Command/icommand.h \
    Game/Command/move.h \
    Game/Command/newgame.h \
    Game/enemyturn.h \
    Game/game.h \
    Game/gameloader.h \
    Game/gamesaver.h \
    Game/iturn.h \
    Game/playerturn.h \
    Log/Observer/iemitter.h \
    Log/Observer/ireceiver.h \
    Log/consolelog.h \
    Log/filelog.h \
    Log/log.h \
    Log/logimpl.h \
    Log/multiplelog.h \
    UDG/fieldwidget.h \
    UDG/untitleddesktopgame.h \
    Units/enemy.h \
    Units/ienemy.h \
    Units/iunit.h \
    Units/player.h

FORMS += \
    UDG/untitleddesktopgame.ui \
